export abstract class ProtocolId {
  static pancakeSwapV3: string = "pancake-swap-v3";
  static uniswapV3: string = "uniswap-v3";
  static aerodromeV3: string = "aerodrome-v3";
  static nuriExchangeV3: string = "nuri-exchange-v3";
  static zebraV3: string = "zebra-protocol-v3";
  static sushiSwapV3: string = "sushi-swap-v3";
  static okuTradeV3: string = "oku-trade-v3";
  static baseSwapV3: string = "base-swap-v3";
  static alienBaseV3: string = "alien-base-v3";
  static uniswapV4: string = "uniswap-v4";
  static squadSwapV3: string = "squad-swap-v3";
  static unchainXV3: string = "unchainx-v3";
  static pancakeSwapV4CL: string = "pancake-v4-cl";
  static uniswapV2: string = "uniswap-v2";
  static sushiSwapV2: string = "sushi-swap-v2";
  static pancakeSwapV2: string = "pancake-swap-v2";
  static baseSwapV2: string = "base-swap-v2";
  static alienBaseV2: string = "alien-base-v2";
  static aerodromeV2: string = "aerodrome-v2";
  static camelotV3: string = "camelot-v3";
  static camelotV2: string = "camelot-v2";
  static ramsesV3: string = "ramses-v3";
  static ramsesV2: string = "ramses-v2";
}
